gh_token: sometoken
repo: git@github.com:crioto/qa-org.git
path: example-test-code
qa_repo: git@github.com:crioto/qa-org.git
qa_path: example-layout
local_path: /tmp
git: git
pk: subutai-qa.2018-09-19.private-key.pem
app_id: 17778
users:
  - crioto